### ISSUE TITLE
Читы гони

### ISSUE THREAD

**Issue by PLAGUEDOCK1233** [Leyn-pl/Snus#1]
Гони читы на снюс

**Comment by Leyn-pl** [comment]
Оставлю это открытым
Если что можете писать мне в лс в дискорде (_LEYN#1092 или одмэн на сервере)
Могу дать один из чит-кодов

**Comment by Leyn-pl** [comment]
В 1.4 вы будете получать один из чит-кодов за прохождение игры

**Comment by TheEE145** [comment]
Тебе лень глянуть в коде все чит коды и что они делают?
