### ISSUE TITLE
Зделать нормально уже

### ISSUE THREAD

**Issue by TheEE145** [Leyn-pl/Snus#5]
Замени уже там где console.log("text" + variable + "text") на `text ${variable}`

Например:

let a = 665;
console.log(`number: ${a}`); 

Вывод будет такой: number: 665

Если скажешь "зачем все и так работает" то потом когда кода будет много читабельность будет клоунской

P.s. гитхаб шиз и не может показать символ `

**Comment by Leyn-pl** [comment]
> читабельность будет клоунской

Если бы мне было не пофиг я бы уже переделал

**Comment by TheEE145** [comment]
Тоесть, тебе пофиг на игру которую создал ты?

**Comment by TheEE145** [comment]
Вроде да
