### ISSUE TITLE
Генерация рандом чит кодов

### ISSUE THREAD

**Issue by TheEE145** [Leyn-pl/Snus#6]
Вместо имён чит кодов юзай math.random() чтобы невозможно было просто глянуть в код и знать все чит коды

**Comment by TheEE145** [comment]
`const random = (min, max) => {
  return Math.floor(Math.random() * (max - min + 1)) + min;
} `

**Comment by Leyn-pl** [comment]
Так их же будет невозможно использовать потом если перезагрузить вкладку, будет каждый раз новый и зачем

**Comment by Leyn-pl** [comment]
Кто хочет пусть смотрит в код, ну молодец что могу сделать только похвалить за находчивость

**Comment by TheEE145** [comment]
Ладно
